[package]
name = "rdwm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xcb = {version="1.6.0", features = ["xkb"]}
xkbcommon = { version = "0.9", features = ["x11"] }
