[package]
name = "rdwm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
saphyr = "0.0.6"
xcb = {version="1.2.0", features = ["xkb"]}
